theme = "rose_pine_moon"
[editor]
auto-save = true
cursorline = true
gutters =["diagnostics", "line-numbers"]
line-number = "absolute"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

