[[language]]
name = "nix"
language-servers = ["nil"]
roots = ["flake.nix", "default.nix", "shell.nix"]

[language-server.nil]
command = "nil"
args = ["--stdio"]

[[language]]
name = "go"
language-servers = ["gopls"]
formatter = { command = "gofmt" }

[language-server.gopls]
command = "gopls"

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{}"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{}"] }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

